### ISSUE TITLE
Error in Authorization

### ISSUE THREAD

**Issue by teramonagi** [dichika/myFitbit#1]
When I tried to use `getToken()` function, I got the following error:

``` r
fitbit_token <- getToken(key, secret)
```

<img width="444" alt="default" src="https://cloud.githubusercontent.com/assets/683736/16391529/8ef93fea-3ce2-11e6-8d64-4ab36adae3d9.png">

Could you fix pls?

**Comment by teramonagi** [comment]
This error was the change of Fitbit API specification.

We have to set redirect URL(Callback URL) on dev.fitbit.com for your application as 
- http://localhost:1410/

not
- http://localhost:1410

Bye.

**Comment by dichika** [comment]
Thanks!
